name: Auto Deploy hugo
on: [push]
env:
  TZ: Asia/Shanghai
jobs:
  HugoAutoDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.108.0'
          extended: true
      - name: Build 
        run: hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }} # secret 中设置好私钥
          external_repository: KitayamAsuka/KitayamAsuka.github.io  # Page 仓库
          publish_branch: main  # Page 仓库的分支
          publish_dir: ./public # 静态网页路径
          cname: kitasuna.tk
